export const FETCH_IN_THEATER = 'FETCH_MOVIES_IN_THEATER';
export const FETCH_IN_THEATER_SUCCESS = 'FETCH_MOVIES_IN_THEATER_SUCCESS';
export const FETCH_IN_THEATER_FAIL = 'FETCH_MOVIES_IN_THEATER_FAIL';
